"""Example tyro YAML

Unused but can be loaded with default=tyro.from_yaml(TrainConfig, yaml_filepath) in main.py
or by adding filepath logic to get_default_config in configs.py.

For example in get_default_config you could grab a yaml path from an env variable and return 
tyro.from_yaml(TrainConfig, env_var_yaml_path). Then set the env variable in a script.
"""
!dataclass:TrainConfig
hellaswag_eval_interval: 500
checkpoint_interval: 1000
batch_size: 128
train_steps: 100000
compute_dtype: float32
params_dtype: float32
optimizer: !dataclass:OptimizerConfig
    type: "adamw"
    learning_rate: 0.001
    warmup_steps: 1000
    weight_decay: 0.1
wandb: !dataclass:WandbConfig
    mode: online
model: !dataclass:ModelConfig
    block_size: 2048
    scan_layers: False
