# tyro YAML.
!dataclass:TrainConfig
hellaswag_eval_interval: 500
checkpoint_interval: 1000
batch_size: 1024
train_steps: 100000
compute_dtype: bfloat16
params_dtype: bfloat16
optimizer: !dataclass:OptimizerConfig
    type: "psgd_affine"
    learning_rate: 0.001
    warmup_steps: 0
    weight_decay: 0.1
    grad_clip: 1.0
    gradient_accumulation_steps: 1
    betas:
      - 0.9
      - 0.95
    nesterov: False
    preconditioner_update_probability: 1.0
    max_size_triangular: 16384
    max_skew_triangular: 16
    precond_lr: 0.1
    precond_init_scale: 0.01
    preconditioner_dtype: bfloat16
wandb: !dataclass:WandbConfig
    entity: evanatyourservice
    mode: online
model: !dataclass:ModelConfig
    block_size: 1024
