# tyro YAML.
!dataclass:TrainConfig
hellaswag_eval_interval: 500
checkpoint_interval: 1000
batch_size: 128
train_steps: 100000
compute_dtype: float32
params_dtype: float32
optimizer: !dataclass:OptimizerConfig
    type: "psgd_affine"
    learning_rate: 0.001
    warmup_steps: 1000
    weight_decay: 0.1
    grad_clip: 1.0
    gradient_accumulation_steps: 1
    b1: 0.9
    b2: 0.95
    nesterov: False
    preconditioner_update_probability: 0.5
    max_size_triangular: 8192
    max_skew_triangular: 16
    precond_lr: 0.1
    precond_init_scale: 1.0
    preconditioner_dtype: float32
wandb: !dataclass:WandbConfig
    entity: evanatyourservice
    mode: online
