# tyro YAML.
!dataclass:TrainConfig
shuffle_buffer_size: 1024
eval_interval: 250
eval_steps: 16
hs_eval_steps: 16
keep_checkpoints: 0
batch_size: 128
train_steps: 50000
bfloat16_compute: False
optimizer: !dataclass:OptimizerConfig
    type: "adamw"
    learning_rate: 0.001
    warmup_steps: 1000
    weight_decay: 0.1
    grad_clip: 1.0
    gradient_accumulation_steps: 1
    betas:
      - 0.9
      - 0.95
wandb: !dataclass:WandbConfig
    entity: evanatyourservice
    project: owt
    mode: online
model: !dataclass:GPT2Config
    vocab_size: 50304  # divisible by 64
    n_positions: 1024
    n_embd: 768
    n_layer: 12
    n_head: 12
    n_inner: 3072
    activation_function: "gelu_new"
    resid_pdrop: 0.0
    embd_pdrop: 0.0
    attn_pdrop: 0.0
    layer_norm_epsilon: 0.00001
    initializer_range: 0.01
    summary_type: "cls_index"
    summary_use_proj: True
    summary_activation: None
    summary_proj_to_labels: True
    summary_first_dropout: 0.0
    scale_attn_weights: True
    use_cache: False
    bos_token_id: 50256
    eos_token_id: 50256
    scale_attn_by_inverse_layer_idx: True
    reorder_and_upcast_attn: True