# tyro YAML.
!dataclass:TrainConfig
hellaswag_eval_interval: 1000
checkpoint_interval: 0
batch_size: 128
train_steps: 50000
compute_dtype: bfloat16
params_dtype: bfloat16
optimizer: !dataclass:OptimizerConfig
    type: "affine"
    learning_rate: 0.001
    warmup_steps: 512
    weight_decay: 0.01
    grad_clip: 0.0
    gradient_accumulation_steps: 1
    betas:
      - 0.9
      - 0.95
    nesterov: false
    preconditioner_update_probability: 1.0
    psgd_use_hessian: False
    max_size_triangular: 1000000000
    max_skew_triangular: 0
    precond_lr: 0.1
    precond_init_scale: 1.0
    preconditioner_dtype: bfloat16
wandb: !dataclass:WandbConfig
    entity: evanatyourservice
    mode: online
model: !dataclass:ModelConfig
    huggingface_model_name: "gpt2"
    use_scan_mlp: False
    block_size: 1024
