# tyro YAML.
!dataclass:TrainConfig
hellaswag_eval_interval: 500
checkpoint_interval: 1000
batch_size: 256
train_steps: 50000
compute_dtype: bfloat16
params_dtype: float32
optimizer: !dataclass:OptimizerConfig
    type: "psgd_affine"
    learning_rate: 0.003
    warmup_steps: 0
    weight_decay: 0.01
    grad_clip: 1.0
    gradient_accumulation_steps: 1
    betas:
      - 0.9
      - 0.95
    nesterov: False
    preconditioner_update_probability: 1.0
    max_size_triangular: 8192
    max_skew_triangular: 16
    precond_lr: 0.1
    precond_init_scale: 0.1
    preconditioner_dtype: bfloat16
wandb: !dataclass:WandbConfig
    entity: evanatyourservice
    mode: online
model: !dataclass:ModelConfig
    huggingface_model_name: "gpt2"
    block_size: 1024
    use_scan_mlp: True
    scan_attention_layers: True